### ISSUE TITLE
Basic Layout

### ISSUE THREAD

**Issue by nrenner0211** [nrenner0211/project-3#4]
_stylin_

**Comment by saharsh-solanki** [comment]
can you provide more discription exactly what you want to do

**Comment by nrenner0211** [comment]
This is a project with set teammates for a class, sorry man! This was just meant to get something on the project board

**Comment by saharsh-solanki** [comment]
Ok No problem , i am a software developer having knowladge of almost 20+ Different language and framework if you need any help feel free to contact me . I can help you in many things like Deployment to DIgital ocean using github actions , Django ORM , Django Rest Framework , React JS , React Native , Bootstrap , Material UI etc
